### ISSUE TITLE
Could you possible change the peer dependency of mobx to include version 4?

### ISSUE THREAD

**Issue by richtera** [foxhound87/rfx-core#6]
Currently it says 2.5 || 3.

**Comment by pdfowler** [comment]
I've been looking into this in the last few days and it's not as simple as updating the peer dependency. I've identified the following breaking changes and am working on a PR:

1. the `@toggle` decorator breaks mobx class based stores.
1. `extendObservable` now throws an error if more than one property is defined in the second object.

I think this will require a v2 release, since I'm not sure how to maintain compatibility with both mobx 4 and mobx 2 || 3

I should have an update later today

**Comment by richtera** [comment]
Ok. We're using it with v4. I guess we're not using all those features :)

**Comment by pdfowler** [comment]
@richtera, I've just [posted my PR](https://github.com/foxhound87/rfx-core/pull/7). As long as you're not using the `@toggle` decorator on your stores you should be fine. 

It appears that the `@extend` decorator works fine, but I'm doing some more testing

**Comment by foxhound87** [comment]
@pdfowler thanks for the PR. 
But why you added the `query-string` dependency? 
Also we can use mobx `4.0.0` instad `4.2.0`.

**Comment by foxhound87** [comment]
About the `@toggle` decorator, I was thinking of deprecating/removing it to reduce the bundle size.

**Comment by foxhound87** [comment]
https://github.com/foxhound87/rfx-core/releases/tag/v1.6.0

**Comment by richtera** [comment]
works great! Thank you.
